/* Compiler_Cfg.h -- AUTOSAR Compiler Configuration for host compilation.
 *
 * On the real target this file is generated by DaVinci Configurator and
 * defines memory class qualifiers for every BSW module. For host (vECU)
 * compilation all qualifiers expand to nothing.
 *
 * When building with a real SIP, the SIP's _Compiler_Cfg.h (included by
 * the SIP's Compiler_Cfg.h) provides the bulk of these defines. This
 * file catches any remaining GenData-specific defines.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#ifndef COMPILER_CFG_H
#define COMPILER_CFG_H

#endif /* COMPILER_CFG_H */
