/* Os_Compiler_Cfg.h -- OS Compiler Configuration for host compilation.
 *
 * Normally generated by the MICROSAR OS configurator. For host (vECU)
 * compilation all OS memory class qualifiers are empty.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#ifndef OS_COMPILER_CFG_H
#define OS_COMPILER_CFG_H

#endif /* OS_COMPILER_CFG_H */
