#!/usr/bin/env python3
"""Generate a C stub file for unresolved application-layer symbols.

Usage:
    python3 generate_appl_stubs.py <dylib_path> <output_c_path>

Extracts undefined symbols from a shared library via `nm -u`, filters out
system/libc/compiler symbols, and generates void-returning C stubs for the
remainder. These stubs allow the vECU dylib to be loaded by vecu-loader
without the real application SWC code.

SPDX-License-Identifier: MIT OR Apache-2.0
"""

import subprocess
import sys
import re
import os

SYSTEM_PREFIXES = {
    "___", "_objc_", "_OBJC_", "_dyld_",
    "dyld_", "_dispatch_", "_os_", "_xpc_",
    "_swift_", "_Block_", "_NSConcreteGlobal",
    "_NSConcreteStack", "__NSConcreteGlobal",
    "__NSConcreteStack", "_kCF", "_CF",
}

LIBC_SYMBOLS = {
    "_abort", "_abs", "_atof", "_atoi", "_atol",
    "_bzero", "_calloc", "_ceil", "_close", "_exit",
    "_fabs", "_fclose", "_fflush", "_fgets", "_floor",
    "_fopen", "_fprintf", "_fputc", "_fputs", "_fread",
    "_free", "_fseek", "_ftell", "_fwrite", "_getenv",
    "_htonl", "_htons", "_inet_addr", "_inet_ntoa",
    "_isalnum", "_isalpha", "_isdigit", "_isspace",
    "_longjmp", "_malloc", "_memchr", "_memcmp",
    "_memcpy", "_memmove", "_memset", "_ntohl", "_ntohs",
    "_open", "_perror", "_pow", "_printf", "_puts",
    "_qsort", "_read", "_realloc", "_remove", "_rename",
    "_setjmp", "_snprintf", "_sprintf", "_sqrt",
    "_srand", "_sscanf", "_stderr", "_stdin", "_stdout",
    "_strcat", "_strchr", "_strcmp", "_strcpy",
    "_strftime", "_strlen", "_strncat", "_strncmp",
    "_strncpy", "_strrchr", "_strstr", "_strtod",
    "_strtol", "_strtoul", "_strtoll", "_strtoull",
    "_tolower", "_toupper",
    "_vfprintf", "_vprintf", "_vsnprintf", "_vsprintf",
    "_write", "_rand",
}


def is_system_symbol(sym: str) -> bool:
    """Return True if the symbol is a system/compiler/libc symbol."""
    for prefix in SYSTEM_PREFIXES:
        if sym.startswith(prefix):
            return True
    if sym in LIBC_SYMBOLS:
        return True
    if sym.startswith("_$") or sym.startswith("__Z"):
        return True
    return False


def extract_undefined(dylib_path: str) -> list[str]:
    """Extract undefined symbols from a dylib using nm."""
    result = subprocess.run(
        ["nm", "-u", dylib_path],
        capture_output=True, text=True, check=True,
    )
    symbols = []
    for line in result.stdout.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        sym = line.split()[-1] if " " in line else line
        if sym and not is_system_symbol(sym):
            symbols.append(sym)
    return sorted(set(symbols))


DATA_PATTERNS = re.compile(
    r'(Config|Cfg$|_Cfg_|Table|FctPtr|Array|Buffer|_Count$|_Size$|'
    r'PCConfig|PCPartitionConfig|_Map$|_Mapping$|Layout|'
    r'DefaultValue|_Ram$|_Rom$|DeviceConfiguration)',
    re.IGNORECASE,
)

FUNC_PATTERNS = re.compile(
    r'(Init|Main|Function|Shutdown|Event|Callout|Notification|'
    r'Indication|Confirmation|ReadData|WriteData|CheckRead|'
    r'Start|Stop|_Cbk|_Trigger|SetProgrammable|OnEnter|'
    r'ConditionCheck|ReturnControlToEcuCbk|FreezeCurrentState|'
    r'ResetToDefault|ShortTermAdjustment|GetCurrentStatus|'
    r'background|Background|Runnable|_Isr$|Interrupt)',
    re.IGNORECASE,
)


def classify_symbol(c_name: str) -> str:
    """Classify a C symbol as 'func' or 'data' based on naming heuristics."""
    if FUNC_PATTERNS.search(c_name):
        return "func"
    if DATA_PATTERNS.search(c_name):
        return "data"
    return "func"


def generate_stubs(symbols: list[str], output_path: str) -> None:
    """Generate a C stub file with appropriate stubs for each symbol."""
    func_syms = []
    data_syms = []

    for sym in symbols:
        c_name = sym[1:] if sym.startswith("_") else sym
        if not c_name or not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', c_name):
            continue
        kind = classify_symbol(c_name)
        if kind == "data":
            data_syms.append(c_name)
        else:
            func_syms.append(c_name)

    with open(output_path, "w") as f:
        f.write("/* vecu_appl_stubs.c — Auto-generated application-layer stubs.\n")
        f.write(" *\n")
        f.write(" * Generated by tools/generate_appl_stubs.py\n")
        f.write(" * These stubs provide no-op implementations for application-layer\n")
        f.write(" * symbols that the MICROSAR BSW references but are not needed for\n")
        f.write(" * basic vECU lifecycle testing.\n")
        f.write(" *\n")
        f.write(" * SPDX-License-Identifier: MIT OR Apache-2.0\n")
        f.write(" */\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")

        total = len(func_syms) + len(data_syms)
        f.write(f"/* {total} stubs: {len(func_syms)} functions, "
                f"{len(data_syms)} data */\n\n")

        if data_syms:
            f.write("/* --- Data symbols (zero-initialized) --- */\n\n")
            for name in data_syms:
                f.write(f"uint8_t {name}[256];\n")
            f.write("\n")

        if func_syms:
            f.write("/* --- Function symbols (no-op) --- */\n\n")
            for name in func_syms:
                f.write(f"void {name}(void) {{ }}\n")

    print(f"Generated {total} stubs ({len(func_syms)} func, "
          f"{len(data_syms)} data) in {output_path}")


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <dylib_path> <output_c_path>")
        sys.exit(1)

    dylib_path = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.exists(dylib_path):
        print(f"Error: {dylib_path} not found")
        sys.exit(1)

    symbols = extract_undefined(dylib_path)
    print(f"Found {len(symbols)} unresolved non-system symbols")
    generate_stubs(symbols, output_path)


if __name__ == "__main__":
    main()
