# Auto-generated list of configured BSW modules (from GenData *_Cfg.h).
# Re-run discover_modules.sh to regenerate.
set(BSW_CONFIGURED_MODULES
    Adc
    BmcLibWrapper
    BswM
    BswM_Private
    CanIf
    CanNm
    CanSM
    CanTSyn
    CanTp
    Can
    ComM
    ComM_Private
    ComStack
    ComXf_Compiler
    Com
    Crc
    CryIf
    Crypto_30_vHsm
    Csm
    DcaRemoteVdpRte
    Dcm
    Dem
    Det
    Det_Private
    Dio_30_Vtt
    Dlt
    DoIP
    E2EXf_Compiler
    EcuM
    EcuM_Init
    EthIf_Bmc
    EthIf
    EthSM
    EthTSyn
    Eth_30_Vtt
    FblBmHdr
    Fee_30_FlexNor
    Fls_30_vMemAccM
    Fls
    Gpt
    Icu
    IdsM
    IpBase
    IpduM
    KeyM
    LdCom
    LinIf
    LinSM
    LinTp
    Lin
    Mcu_30_Vtt
    MemIf
    Nm
    NvM
    Os_AccessCheck
    Os_Alarm
    Os_Application
    Os_Barrier
    Os
    Os_Compiler
    Os_Core
    Os_Counter
    Os_Error
    Os_Hal
    Os_Hal_Core
    Os_Hal_Entry
    Os_Hal_Interrupt
    Os_Hal_MemoryProtection
    Os_Hal_Vtt
    Os_Hook
    Os_Interrupt
    Os_Ioc
    Os_MemoryProtection
    Os_ScheduleTable
    Os_Scheduler
    Os_ServiceFunction
    Os_Stack
    Os_TimingProtection
    Os_Trace
    Os_XSignal
    PduR
    Port_30_Vtt
    Pwm
    Rte
    Rte_Compiler
    Rtm
    Sbc_30_Raa271084
    Sd
    SecOC
    SoAd
    SomeIpTp
    SomeIpXf_Compiler
    Spi
    Ssa
    StbM
    TcpIpXcp
    TcpIp
    UdpNm
    VdpCmRemote
    VdpCmRemote_DcaRemoteHandler
    VttCntrl_Adc
    VttCntrl_Can
    VttCntrl
    VttCntrl_Dio
    VttCntrl_Eth
    VttCntrl_Fls
    VttCntrl_Gpt
    VttCntrl_Icu
    VttCntrl_Pwm
    VttCntrl_SysVar
    VttCntrl_vMem
    WdgM
    Wdg_30_Vtt
    Xcp
    vCan_30_Rscanfd
    vFsmLib
    vLinFp_30_Rh850
    vLinkGen
    vMemAccM
    vMem_30_Rh850Faci01
    vMem_30_Vtt
    vMem_30_XXspi01
    vRpcProxy
    veGwM
    veGwM_EventBuffer
)
